Repository move4mobile/geekbites, pull requests merged in 2021-03, with the labels that each got.

#139 Automatic Dependabot updates
  package-lock.json
  package.json
Labels: dependencies

#163 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#168 ci: update workflows to target 'main'
  .github/workflows/cicd.yml
  .github/workflows/codeql-analysis.yml
  package.json
Labels: enhancement

#145 feat: new blogpost 'Modern web API's'
  src/_data/people.json
  src/assets/web-APIs/notifications.jpg
  src/posts/2021-02-25-Web-APIs.md
Labels: blogpost, enhancement

#173 fix: comments link for Web API post by changing title
  src/posts/2021-02-25-web-apis.md
Labels: bug

#170 Update the README file
  README.md
Labels: enhancement

#138 Create 2021-02-15-phaser-blog.md
  .vscode/settings.json
  src/posts/2021-02-15-phaser-blog.md
Labels: blogpost

#174 Next release to production
  .vscode/settings.json
  README.md
  src/posts/2021-02-15-phaser-blog.md
  src/posts/2021-02-25-web-apis.md
Labels: blogpost
