Repository move4mobile/geekbites, pull requests merged in 2022-01, with the labels that each got.

#269 build(deps-dev): replace eleventy-plugin-sass with eleventy-plugin-dart-sass
  .eleventy.js
  package-lock.json
  package.json
Labels: enhancement, dependencies, security

#270 build(deps-dev): bump @11ty/eleventy to 1.0.0
  .eleventy.js
  index.html
  package-lock.json
  package.json
  src/_includes/layouts/post.njk
  src/_includes/postslist-content.njk
  src/posts/posts.json
Labels: enhancement, dependencies

#273 Update default node version to 16
  .github/workflows/cicd.yml
  .github/workflows/nightly.yml
  .nvmrc
  package-lock.json
Labels: enhancement
